// Apple HKWorkoutActivityType raw values, mirrored from
// node_modules/@kingstinct/react-native-healthkit/src/types/Workouts.ts on the
// iOS side. Kept here so the MCP `schema` resource can render a name<->id table
// for the AI when it constructs SQL like
// `WHERE workout_activity_type_id = 13` ("cycling").
//
// Apple may add new ids over time; the iOS client forwards them as-is and the
// backend stores them without a CHECK constraint. Add new entries here so the
// AI sees them in the schema resource.
export interface WorkoutActivityType {
  id:   number;
  name: string;
}

export const WORKOUT_ACTIVITY_TYPES: readonly WorkoutActivityType[] = [
  { id: 1,    name: 'americanFootball' },
  { id: 2,    name: 'archery' },
  { id: 3,    name: 'australianFootball' },
  { id: 4,    name: 'badminton' },
  { id: 5,    name: 'baseball' },
  { id: 6,    name: 'basketball' },
  { id: 7,    name: 'bowling' },
  { id: 8,    name: 'boxing' },
  { id: 9,    name: 'climbing' },
  { id: 10,   name: 'cricket' },
  { id: 11,   name: 'crossTraining' },
  { id: 12,   name: 'curling' },
  { id: 13,   name: 'cycling' },
  { id: 14,   name: 'dance' },
  { id: 15,   name: 'danceInspiredTraining' },
  { id: 16,   name: 'elliptical' },
  { id: 17,   name: 'equestrianSports' },
  { id: 18,   name: 'fencing' },
  { id: 19,   name: 'fishing' },
  { id: 20,   name: 'functionalStrengthTraining' },
  { id: 21,   name: 'golf' },
  { id: 22,   name: 'gymnastics' },
  { id: 23,   name: 'handball' },
  { id: 24,   name: 'hiking' },
  { id: 25,   name: 'hockey' },
  { id: 26,   name: 'hunting' },
  { id: 27,   name: 'lacrosse' },
  { id: 28,   name: 'martialArts' },
  { id: 29,   name: 'mindAndBody' },
  { id: 30,   name: 'mixedMetabolicCardioTraining' },
  { id: 31,   name: 'paddleSports' },
  { id: 32,   name: 'play' },
  { id: 33,   name: 'preparationAndRecovery' },
  { id: 34,   name: 'racquetball' },
  { id: 35,   name: 'rowing' },
  { id: 36,   name: 'rugby' },
  { id: 37,   name: 'running' },
  { id: 38,   name: 'sailing' },
  { id: 39,   name: 'skatingSports' },
  { id: 40,   name: 'snowSports' },
  { id: 41,   name: 'soccer' },
  { id: 42,   name: 'softball' },
  { id: 43,   name: 'squash' },
  { id: 44,   name: 'stairClimbing' },
  { id: 45,   name: 'surfingSports' },
  { id: 46,   name: 'swimming' },
  { id: 47,   name: 'tableTennis' },
  { id: 48,   name: 'tennis' },
  { id: 49,   name: 'trackAndField' },
  { id: 50,   name: 'traditionalStrengthTraining' },
  { id: 51,   name: 'volleyball' },
  { id: 52,   name: 'walking' },
  { id: 53,   name: 'waterFitness' },
  { id: 54,   name: 'waterPolo' },
  { id: 55,   name: 'waterSports' },
  { id: 56,   name: 'wrestling' },
  { id: 57,   name: 'yoga' },
  { id: 58,   name: 'barre' },
  { id: 59,   name: 'coreTraining' },
  { id: 60,   name: 'crossCountrySkiing' },
  { id: 61,   name: 'downhillSkiing' },
  { id: 62,   name: 'flexibility' },
  { id: 63,   name: 'highIntensityIntervalTraining' },
  { id: 64,   name: 'jumpRope' },
  { id: 65,   name: 'kickboxing' },
  { id: 66,   name: 'pilates' },
  { id: 67,   name: 'snowboarding' },
  { id: 68,   name: 'stairs' },
  { id: 69,   name: 'stepTraining' },
  { id: 70,   name: 'wheelchairWalkPace' },
  { id: 71,   name: 'wheelchairRunPace' },
  { id: 72,   name: 'taiChi' },
  { id: 73,   name: 'mixedCardio' },
  { id: 74,   name: 'handCycling' },
  { id: 75,   name: 'discSports' },
  { id: 76,   name: 'fitnessGaming' },
  { id: 77,   name: 'cardioDance' },
  { id: 78,   name: 'socialDance' },
  { id: 79,   name: 'pickleball' },
  { id: 80,   name: 'cooldown' },
  { id: 82,   name: 'swimBikeRun' },
  { id: 83,   name: 'transition' },
  { id: 84,   name: 'underwaterDiving' },
  { id: 3000, name: 'other' }
];
