export const SLEEP_STAGES: Record<number, string> = {
  0: 'In Bed',
  1: 'Asleep',
  2: 'Awake',
  3: 'Core',
  4: 'Deep',
  5: 'REM',
};

export const WORKOUT_NAMES: Record<number, string> = {
  1: 'American Football',
  2: 'Archery',
  3: 'Australian Football',
  4: 'Badminton',
  5: 'Baseball',
  6: 'Basketball',
  7: 'Bowling',
  8: 'Boxing',
  9: 'Climbing',
  10: 'Cricket',
  11: 'Cross Training',
  12: 'Curling',
  13: 'Cycling',
  14: 'Dance',
  15: 'Disc Sports',
  16: 'Elliptical',
  17: 'Equestrian Sports',
  18: 'Fencing',
  19: 'Fishing',
  20: 'Functional Strength',
  21: 'Golf',
  22: 'Gymnastics',
  23: 'Handball',
  24: 'Hiking',
  25: 'Hockey',
  26: 'Hunting',
  27: 'Lacrosse',
  28: 'Martial Arts',
  29: 'Mind and Body',
  30: 'Mixed Metabolic Cardio',
  31: 'Paddle Sports',
  32: 'Play',
  33: 'Preparation and Recovery',
  34: 'Racquetball',
  35: 'Rowing',
  36: 'Rugby',
  37: 'Running',
  38: 'Sailing',
  39: 'Skating Sports',
  40: 'Snow Sports',
  41: 'Soccer',
  42: 'Softball',
  43: 'Squash',
  44: 'Stair Climbing',
  45: 'Surfing Sports',
  46: 'Swimming',
  47: 'Table Tennis',
  48: 'Tennis',
  49: 'Track and Field',
  50: 'Traditional Strength',
  51: 'Volleyball',
  52: 'Walking',
  53: 'Water Fitness',
  54: 'Water Polo',
  55: 'Water Sports',
  56: 'Wrestling',
  57: 'Yoga',
  58: 'Barre',
  59: 'Core Training',
  60: 'Cross Country Skiing',
  61: 'Downhill Skiing',
  62: 'Flexibility',
  63: 'HIIT',
  64: 'Jump Rope',
  65: 'Kickboxing',
  66: 'Pilates',
  67: 'Snowboarding',
  68: 'Stairs',
  69: 'Step Training',
  70: 'Wheelchair Walk Pace',
  71: 'Wheelchair Run Pace',
  72: 'Tai Chi',
  73: 'Mixed Cardio',
  74: 'Hand Cycling',
  75: 'Disc Sports',
  76: 'Fitness Gaming',
  77: 'Cardiodance',
  78: 'Social Dance',
  79: 'Pickleball',
  80: 'Cooldown',
  82: 'Swim-Bike-Run',
  84: 'Underwater Diving',
  3000: 'Other',
};

export interface MetricDefinition {
  dataType: string;
  defaultAggregation: 'avg' | 'sum' | 'min' | 'max' | 'latest';
  unit: string;
  perDay?: 'sum' | 'avg' | 'latest';
}

export const METRIC_MAP: Record<string, MetricDefinition> = {
  steps: {
    dataType: 'HKQuantityTypeIdentifierStepCount',
    defaultAggregation: 'sum',
    unit: 'count',
    perDay: 'sum',
  },
  active_energy: {
    dataType: 'HKQuantityTypeIdentifierActiveEnergyBurned',
    defaultAggregation: 'sum',
    unit: 'kcal',
    perDay: 'sum',
  },
  distance: {
    dataType: 'HKQuantityTypeIdentifierDistanceWalkingRunning',
    defaultAggregation: 'sum',
    unit: 'm',
    perDay: 'sum',
  },
  heart_rate: {
    dataType: 'HKQuantityTypeIdentifierHeartRate',
    defaultAggregation: 'avg',
    unit: 'bpm',
    perDay: 'avg',
  },
  resting_hr: {
    dataType: 'HKQuantityTypeIdentifierRestingHeartRate',
    defaultAggregation: 'latest',
    unit: 'bpm',
    perDay: 'latest',
  },
  hrv: {
    dataType: 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN',
    defaultAggregation: 'avg',
    unit: 'ms',
    perDay: 'avg',
  },
  spo2: {
    dataType: 'HKQuantityTypeIdentifierOxygenSaturation',
    defaultAggregation: 'avg',
    unit: '%',
    perDay: 'avg',
  },
  respiratory_rate: {
    dataType: 'HKQuantityTypeIdentifierRespiratoryRate',
    defaultAggregation: 'avg',
    unit: 'breaths/min',
    perDay: 'avg',
  },
  weight: {
    dataType: 'HKQuantityTypeIdentifierBodyMass',
    defaultAggregation: 'latest',
    unit: 'kg',
    perDay: 'latest',
  },
  body_fat: {
    dataType: 'HKQuantityTypeIdentifierBodyFatPercentage',
    defaultAggregation: 'latest',
    unit: '%',
    perDay: 'latest',
  },
};
